#!/usr/bin/env bash

source "$LAZYMAP_DIR/lib/colors.sh"

display_ascii_art() {
    echo -e "${GREEN}"
    echo " ████                                                                     "
    echo "░░███                                                                     v1.0"
    echo " ░███   ██████    █████████ █████ ████ █████████████    ██████   ████████ "
    echo " ░███  ░░░░░███  ░█░░░░███ ░░███ ░███ ░░███░░███░░███  ░░░░░███ ░░███░░███"
    echo " ░███   ███████  ░   ███░   ░███ ░███  ░███ ░███ ░███   ███████  ░███ ░███"
    echo " ░███  ███░░███    ███░   █ ░███ ░███  ░███ ░███ ░███  ███░░███  ░███ ░███"
    echo " █████░░████████  █████████ ░░███████  █████░███ █████░░████████ ░███████ "
    echo "░░░░░  ░░░░░░░░  ░░░░░░░░░   ░░░░░███ ░░░░░ ░░░ ░░░░░  ░░░░░░░░  ░███░░░  "
    echo "                             ███ ░███                            ░███     "
    echo "                            ░░██████                             █████    "
    echo "                             ░░░░░░                             ░░░░░     "
    echo ""
    echo -e "                    ${YELLOW}[network penetration testing kit]${NC}    "
    echo ""
    echo ""
}

display_help() {
    echo -e "${GREEN}Title: lazymap (Project0x01)${NC}"
    echo -e "${GREEN}Author: Evan Ricafort (Email: root@evanricafort.com | X - @evanricafort | Portfolio - https://evanricafort.com)${NC}"
    echo -e "${GREEN}Description: lazymap is a single command-line tool made for network penetration testing. It combines multiple selected NMAP scripts, sslscan, ssh-audit, dig, ldapsearch, curl, rpcclient, selected metasploit modules, PRET and wget.${NC}"
    echo ""
    echo -e "${GREEN}--Usage--${NC}"
    echo -e "${GREEN}- ./lazymap.sh -u host <options>${NC}"
    echo -e "${GREEN}- ./lazymap.sh -t hosts <options>${NC}"
    echo ""
    echo -e "${GREEN}- Additional options:${NC}"
    echo -e "  ${YELLOW}-1${NC} ${GREEN}for [vulners],${NC}"
    echo -e "  ${YELLOW}-2${NC} ${GREEN}for [vuln],${NC}"
    echo -e "  ${YELLOW}-3${NC} ${GREEN}for both [vulners & vuln] NSE scripts,${NC}"
    echo -e "  ${YELLOW}-4${NC} ${GREEN}for Firewall Evasion Scan,${NC}"
    echo -e "  ${YELLOW}-a${NC} ${GREEN}to exclude the all ports scan and UDP scan.${NC}"
    echo -e "  ${YELLOW}-n${NC} ${GREEN}to add '-n' and '-T4' to nmap command for faster scanning.${NC}"
    echo -e "  ${YELLOW}-k${NC} ${GREEN}to exclude sslscan, ssh-audit, and CheckThatHeaders scans.${NC}"
    echo -e "  ${YELLOW}-b${NC} ${GREEN}to add '-A', '--min-rate 1000' and '--open' for add boost and open ports results only.${NC}"
    echo -e "  ${YELLOW}--pret${NC} ${GREEN}to perform printer security check using PRET (Credits to Jens Mueller).${NC}"
    echo -e "  ${YELLOW}--interface [iface]${NC} ${GREEN}to run Responder on a specified interface.${NC}"
    echo -e "  ${YELLOW}-o [dir]${NC} ${GREEN}to specify a custom output directory (default: results).${NC}"
    echo -e "  ${YELLOW}--exclude-udp${NC} ${GREEN}to exclude UDP scan.${NC}"
    echo -e "  ${YELLOW}--discord${NC} ${GREEN}to send the overall report to your discord server (prompts for the webhook URL).${NC}"
    echo -e "  ${YELLOW}--resume${NC} ${GREEN}to continue an interrupted scan, skipping steps that already finished.${NC}"
    echo -e "  ${YELLOW}--domain [realm]${NC} ${GREEN}Active Directory realm for Kerberos username enumeration (auto-detected when omitted).${NC}"
    echo -e "  ${YELLOW}--userlist [file]${NC} ${GREEN}username list for Kerberos enumeration (default: extra/wordlists/kerberos_users.txt).${NC}"
    echo -e "  ${YELLOW}--nmap-stall [seconds]${NC} ${GREEN}treat an nmap scan as hung after this long with no progress (default: 120).${NC}"
    echo -e "  ${YELLOW}--no-nmap-watchdog${NC} ${GREEN}disable stall detection and NSE culprit isolation.${NC}"
    echo -e "  ${YELLOW}--script-timeout [time]${NC} ${GREEN}max runtime per NSE script per host (default: 5m; use 0 to disable).${NC}"
    echo -e "  ${YELLOW}--host-timeout [time]${NC} ${GREEN}give up on a host after this long (nmap format, e.g. 30m). Off by default.${NC}"
    echo -e "  ${YELLOW}--ntp-dos${NC} ${GREEN}enable the NTP peer-list module, which can disrupt the target's time service (off by default).${NC}"
    echo -e "  ${YELLOW}--mitm6${NC} ${GREEN}to run the IPv6 DNS Takeover test (mitm6 + ntlmrelayx). Active attack, needs root and --domain.${NC}"
    echo -e "  ${YELLOW}--mitm6-interface [iface]${NC} ${GREEN}interface for mitm6 (defaults to --interface).${NC}"
    echo -e "  ${YELLOW}--mitm6-time [seconds]${NC} ${GREEN}how long to run mitm6 (default: 300).${NC}"
    echo -e "  ${YELLOW}--install-deps${NC} ${GREEN}to automatically install any missing tools (run on its own to set up the machine).${NC}"
    echo -e "  ${YELLOW}-y, --yes${NC} ${GREEN}to answer yes to prompts, including the install prompt.${NC}"
    echo -e "  ${YELLOW}-h${NC} ${GREEN}to display this help message.${NC}"
    echo ""
    echo -e "${GREEN}- Example: ./lazymap.sh -t hosts -12bank --pret --exclude-udp --interface eth0 -o my_scan${NC}"
    echo ""
    echo -e "${GREEN}- Setup: ./lazymap.sh --install-deps installs every missing dependency and exits.${NC}"
    echo ""
    echo -e "${GREEN}- Resume: If a scan is interrupted (Ctrl+C), re-run the same command with --resume${NC}"
    echo -e "${GREEN}  and the same -o directory to pick up where it stopped. Example:${NC}"
    echo -e "${GREEN}    ./lazymap.sh -t hosts -12bank -o my_scan --resume${NC}"
    echo ""
    echo -e "${GREEN}- Reminder: Option -3 may take some time to finish if you have multiple targets.${NC}"
    echo -e "${GREEN}- Note: Run in sudo mode to execute NMAP scripts related to UDP scan and Responder.${NC}"
    exit 0
}
